### ISSUE TITLE
Stateful deployment broken due to an outdated dependency

### ISSUE THREAD

**Issue by trevoruptain** [leegilmorecode/bedrock-knowledge-bases#2]
AWS now requires OpenSearch Serverless to use the FAISS engine, which causes stateful deployment to fail for older versions of `@cdklabs/generative-ai-cdk-constructs`. This was resolved here: https://github.com/awslabs/generative-ai-cdk-constructs/commit/d6b2bf5f6b6e1de892432e5e220d064176809ff8

The fix is running `npm upgrade @cdklabs/generative-ai-cdk-constructs`.

**Comment by leegilmorecode** [comment]
Thank you for pointing this out - I'll fix this later today 🙏

**Comment by leegilmorecode** [comment]
Thank you for pointing this out - it is now resolved
